name: docker

on:
  push:
    tags-ignore:
      - v*-*-*
  pull_request:

jobs:
  build:
    name: Build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.0.1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.2
        with:
          username: sansui233
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: sansui233/proxypool/proxypool
          tag_with_ref: true
